### ISSUE TITLE
[bugreport]: Fehler beim Laden des Cores

### ISSUE THREAD

**Issue by Todayishugebread** [PXAV/kelp#72]
Wenn der Kelp-Core im Pluginordner ist und man den Server startet, dann erscheint eine Fehlermeldung.

ERROR]: Error occurred while enabling Kelp v0.4.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.google.inject.Injector.getInstance(java.lang.Class)" because "de.pxav.kelp.core.KelpPlugin.injector" is null
	at de.pxav.kelp.core.KelpPlugin.logKelpLogo(KelpPlugin.java:149) ~[?:?]
	at de.pxav.kelp.core.KelpPlugin.onEnable(KelpPlugin.java:73) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:520) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:434) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:619) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1010) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at java.lang.Thread.run(Thread.java:833) [?:?]

Das ist die Fehlermeldung.

* Operating system: Linux Ubuntu 20.04
* Java-Version: 1.8
* Kelp-Core-Version: v.0.4.0
* Version-Implementation: 1.8
Danke für eure Aufmerksamkeit

**Comment by PhantomClone** [comment]
Du hast die Kelp implementation für die 1.8, nutzt aber einen Minecraft Server mit der Version 1.17

**Comment by Todayishugebread** [comment]
@PhantomClone der Schritt mit der Implementation war ja noch gar nicht, bis jetzt ging es nur um das Laden des Cores, und auf einem 1.8 Server funktioniert es auch nicht.
